### ISSUE TITLE
[Enhancement] Add New Features to Ask for User Input (IP + Domain) & Output URL for Web Server

### ISSUE THREAD

**Issue by officialjm** [stolenusername/cowitness#1]
Hey! 👋🏼

I have done some testing on this new project personally and thought of some great futures to add to make the tool easier to setup (via user input) and the ability for the program to kill the running DNS process that is created and left when the program is closed.

In this modified code:

- The **_DNSResponseIP_** and **_DNSResponseName_** constants have been changed to variables since their values will be obtained from the user.

- The program now prompts the user to enter the DNS response IP and DNS response name using `fmt.Scanln()`.

- The DNS server process ID is killed using the kill command when the program is closed. This is achieved by adding a defer statement that executes a command to kill the process ID of the program.

- The program outputs a link to the URL that the user can click on. The link is printed to the console using `log.Printf()`

![2023-07-14_15-23](https://github.com/stolenusername/cowitness/assets/20228213/c96a54ea-3b4a-4f5c-a98e-17c8a2eb40e5)

**Comment by officialjm** [comment]
Let me know when I can / am able to make a git pull  / merge request! 🙂 I have the updated Go script source code ready on hand for review.

Find me here 👉🏼 https://www.linkedin.com/in/ofcljm/

**Comment by officialjm** [comment]
Update: Changes have been added and pull request is now pending! See the following for further details: https://github.com/stolenusername/cowitness/pull/3

**Comment by stolenusername** [comment]
Updated with merge.
