### ISSUE TITLE
[Bug] MIT License Not Created on Project

### ISSUE THREAD

**Issue by officialjm** [stolenusername/cowitness#4]
Looks to be that the MIT License was NOT created on this project yet as there is no license file in root directory & link directs to a 404. This is a simple fix on your end :) 

See the following screenshot: 
![License](https://github.com/stolenusername/cowitness/assets/20228213/310b4623-6867-434a-9964-0607cce23bb3)

**Comment by stolenusername** [comment]
Updated with merge.
